name: music
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  freezed_annotation: ^3.1.0
  equatable: ^2.0.8
  injectable: ^2.7.1+4
  get_it: ^9.2.0
  go_router: ^17.0.1
  dio: ^5.9.0
  retrofit: ^4.9.2
  slang: ^4.11.1
  slang_flutter: ^4.11.0
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  logging: ^1.3.0
  collection: ^1.19.1
  package_info_plus: ^9.0.0
  google_sign_in: ^7.2.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.3
  google_fonts: ^7.0.0
  sqflite: ^2.4.1
  path: ^1.9.0
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.2.0
  pretty_dio_logger: ^1.4.0
  native_dio_adapter: ^1.5.0
  infinite_scroll_pagination: ^5.1.1
  just_audio: ^0.9.38
  internet_connection_checker_plus: ^2.9.1+2
  synchronized: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.4
  flutter_gen_runner: ^5.7.0
  flutter_gen_core: ^5.4.0
  injectable_generator: ^2.11.1
  retrofit_generator: ^10.2.1
  json_serializable: ^6.11.3
  go_router_builder: ^4.1.3

flutter_gen:
  output: lib/gen/
  assets:
    outputs:
      package_parameter_enabled: false
  integrations:
    flutter_svg: true

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/png/
    - assets/mp4/
    - assets/svg/
    - assets/jpeg/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
          style: normal
